This gets rid of:
gcc -c -Werror -pedantic-errors -Wfatal-errors -Wall  -Wextra -Wno-unused-parameter -Wshadow -limagequant -O3  lz.c -o out/lz.o
lz.c: In function ‘read_input’:
lz.c:63:25: error: ‘FILE {aka struct _IO_FILE}’ has no member named ‘_file’
 # define _fileno(p) ((p)->_file)
                         ^
lz.c:328:9: note: in expansion of macro ‘_fileno’
   fstat(_fileno(file), &stat);