Have made some of this compile but there is a big imagemagick library change from 6 to 7, and installing 6 will uninstall some packages I'd like to keep
/bin/sh: 1: GraphicsMagick-config: not found
resize.c:6:24: fatal error: magick/api.h: No such file or directory